services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3048:3047"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./env:/app/env:ro

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3048:3047"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./:/app
      - /app/node_modules
      - ./env:/app/env:ro
    command: npm run dev