services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3048:3047"
    env_file:
      - ./env/.env.production
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3049:3000"
    env_file:
      - ./.env.local
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev